# Form implementation generated from reading ui file 'd:\Python\YandexCoffee\UI\main.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CoffeeWidget(QtWidgets.QWidget):
    def setupUi(self, CoffeeWidget):
        CoffeeWidget.setObjectName("CoffeeWidget")
        CoffeeWidget.resize(476, 410)
        self.verticalLayout = QtWidgets.QVBoxLayout(CoffeeWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addButton = QtWidgets.QPushButton(parent=CoffeeWidget)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.editButton = QtWidgets.QPushButton(parent=CoffeeWidget)
        self.editButton.setObjectName("editButton")
        self.horizontalLayout.addWidget(self.editButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(parent=CoffeeWidget)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(CoffeeWidget)
        QtCore.QMetaObject.connectSlotsByName(CoffeeWidget)

    def retranslateUi(self, CoffeeWidget):
        _translate = QtCore.QCoreApplication.translate
        CoffeeWidget.setWindowTitle(_translate("CoffeeWidget", "CoffeeWidget"))
        self.addButton.setText(_translate("CoffeeWidget", "Добавить запись"))
        self.editButton.setText(_translate("CoffeeWidget", "Редактировать"))
